# Workflow de Despliegue de Supabase
name: Supabase

# Se ejecuta en push a main o manualmente
on:
  push:
    branches: [main]
    paths:
      - 'supabase/**'
  pull_request:
    branches: [main]
    paths:
      - 'supabase/**'
  workflow_dispatch: # Permite ejecución manual desde GitHub

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        run: supabase start

      - name: Verify Supabase migrations
        run: |
          supabase db reset
          supabase db lint
          supabase test db

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Production # Usa el entorno de producción para los secretos

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1 # Instala y configura Supabase CLI
        with:
          version: latest # Usa la última versión estable

      - name: Push database changes
        env:
          # Token de acceso para la API de Supabase
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          # Contraseña de la base de datos
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: supabase db push # Aplica las migraciones pendientes
